language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "vladak-github"
    token:
      secure: "kXtW0iVbJD8jl+BumolRXAz3OpXRQgAJN/tidEePlVLDDHYcFYqlOal32GhlTqhByiOlsE62RceZi7iuoQAPyCk0JgM5W2ulbfinwF3UV5Nb5nablD36eW/vhjZ9xl2Witlb8AWFyZ/XLoMgWRa1t4kzA6S1GIH9DJvYjS2YHK13MRrAfDUqYRF5cgXFwciD/J5OZIXsuhwTsWM6I7b0gh0Ma3tAXWeGhKiV1RgSvoSg3Z+YD3oqv12W3u8cAFKVQwDaDnP67AezcvfjeBCNvr3xFlJw7G2dGv5rpE2q7PVPB9nM7Vrnt1ne6w8nsfgXdM0quNTLWnvs2itBrHjc51UoOVKF+LMNUk++dfbq+6jVasbPmPtkniZZigPsCCvY5QhzZJo0CHSu1CDGE0wXqpyeOuZZNEZ60ZUu9iHdt81UCqfUDCuJCVJUcOGkikSE+vIDxEGUuq0FY5ftcLqzfcxmkgBk8Ym1Z6OAUfsKAiyiOztU1fTSpvLooLO1m1M5b11po2n+tvoFqGO67U7Ww6Hxytjx8cg2AztbGohaziyXJDbaNUjpYNBYwKI5X+13dmAh2XUAUsb9kYGwQJxHVYmuyCOHnCMFel/WZA7m1ll+30wpF/Yu19u4dsO3zGZofS87heybbp6dhAl5jztHnqRZNXZXsojBpf4s0aGy/xQ="

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
