language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "vladak-github"
    token:
      secure: "s7wSQ/RcmxBJDDWS3ht6tDAvQQVi3vOPK0lJJj8cDeWFe2KbN67yORDZNteM36LI0vQ9lWNe8FDyOShmxSiiP3Bln1HgWYNS35hBEUrTvIOBS217n4XIAPFGXFcKHq094iPqXsoJf1WiVDdB3++9iiXQ1q5D/P1jeUnfbQNzRdTprNDk0nGuRmhk6AxGraZB0i877E0UlLdS7ZVN9pJBL6qGu49wuhITqNNVZIMfZ6m3fNQBWE1ajoxq9OUG4MlaIf3avV/0r0b4U5hl09AFbhP9ZhjLrleGa2A4bb7KC03FsZMpwQVVAjmPAlWi+tvDjuH0WlxLcypHwZc6DO/M/MfpQGlnZhwheueFT3GMjr1Hy4DoGp7NjIUvcMUYm6UrY8Xv2r8KUyZ+itRodNFbQdAf0Of1kTuG6gFVZAeEO7aw91Nxc8HAl5u+eE9SvyAU8Gti7I9B0J3z0JafJ4KhG8RrwevrZV6M0GqflrPK6IHsgD0QCqRtT226r4FtsMG70xRRda6OOLsPdp79E6Kk68EfJNVaGaamIhUMnPmRaIMWR6bDktXHkWWduWIVfmGIbXdTYxSSz+xMFWcaaZMDyW/FAzEDoig2MIFLjY6hTPVeCfQxetPYCmjNw9ywxClU9Ce0qmNTxstaR9hczKWcx2Wf6KcgXqxC6r813u5dS+g="

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
