language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "vladak-github"
    token:
      secure: "Csdunj28cRV/Hs+8ogi15lLS8/CC+TRVVbOpYWtJb09U39uTYEezkC3pJXE1qIVr4KgjxRSEqP/7MkIOlbavCwbHa2p9NAA16Gyl2CVvrTLzUK3OFKashF4ZvjLhl8RVRYDJds7kfUvoyxb4xH8om+42sWNCa6DCuXN3h/+Rj0ToKaArQQzjDaoMoHPV9FiDRw78PINq2IPIxWdGcoj4LcvtuWwQBkUD9lu6+PnTjpB0/VrGra2RBsAUi5DydnqSLrbyiImQcxGWal7w9kps6PBW00fZZyHUAiUn2qLAGfWPNc+rY9ymS6jwxCJgMu1VNEK+G4/T3j0l3dDJZUubxALR5whEMnUvHnoTc5Duuv0ywXYLiTWnQpre8lstQy3alv4JEeeck1ukppr3/jfFy5HDLPWsfuWSt9ks0aICZU2ODHOcStqfC4heROb1sA3rKhaFAScnSYgfiPeuDBKyCejqwDDCVjc0qyw7Jw47qkt85RVlwgprot69PFAuxNCjBCm3HxpUscDqf0CY+UhV8l+8zvhu54X61lWDTuWryVEEyUWb1O+hv7ceLkkNoa0LK9L+4Zuih1f/5O/50UET1OafzKUcwP/BCEUHaRG+Plzzwmi7eVdScbj5ughZY6nxWy25dFz9GJHppTKcLPl6DwAUjMci29o1KioukT7oP64="

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
